baseURL = "https://park.is/"
languageCode = "en-us"
title = "Park's Blog"
theme = "park-blog-theme"
paginate = 5
googleAnalytics = "UA-170280017-1"

[taxonomies]
category = "categories"

[markup]

  [markup.highlight]
  style = "colorful"

  [markup.goldmark.renderer]
  unsafe = true