baseURL: "https://park-blog.netlify.app/"
languageCode: "en-us"
title: "Park's Blog"
taxonomies:
  category: categories
theme: "park-blog-theme"
params:
  logo_image: /images/logo_park.png
markup:
  highlight:
    style: colorful
paginate: 5
googleAnalytics: "UA-170280017-1"
disqusShortname: "park"